const script = [
  "delete from users",
  "delete from songs",
  "delete from playlists",
  "DROP SEQUENCE ARTIST_LISTS_ID_SEQ",
  "DROP SEQUENCE PLAYLISTS_PLAYLIST_ID_SEQ",
  "DROP SEQUENCE PLAYLIST_SONGS_ID_SEQ",
  "DROP SEQUENCE SONGS_SONG_ID_SEQ",
  "DROP SEQUENCE SONG_LIKES_ID_SEQ",
  "DROP SEQUENCE USERS_USER_ID_SEQ",
  "DROP SEQUENCE USER_COMMENTS_ID_SEQ",
  "CREATE SEQUENCE artist_lists_id_seq START WITH 1 MINVALUE 1 NOCACHE ORDER",
  "CREATE SEQUENCE playlist_songs_id_seq START WITH 1 MINVALUE 1 NOCACHE ORDER",
  "CREATE SEQUENCE playlists_playlist_id_seq START WITH 1 MINVALUE 1 NOCACHE ORDER",
  "CREATE SEQUENCE song_likes_id_seq START WITH 1 MINVALUE 1 NOCACHE ORDER",
  "CREATE SEQUENCE songs_song_id_seq START WITH 1 MINVALUE 1 NOCACHE ORDER",
  "CREATE SEQUENCE user_comments_id_seq START WITH 1 MINVALUE 1 NOCACHE ORDER",
  "CREATE SEQUENCE users_user_id_seq START WITH 1 MINVALUE 1 NOCACHE ORDER",
];

module.exports = script;
